version: '2.3'
services:
  tensorflow: 
    container_name: tensorflow_1
    image: tensorflow/tensorflow:latest-gpu-py3-jupyter
    volumes:
      - /path/to/data:/mnt
    runtime: nvidia
    tty: true
    command: /bin/bash
    ports:
      - 8888:8888
